In [1]:
import torch
import torch.nn as nn
import numpy as np

# ============================================================
# TASK 1: Training with PyTorch (One Iteration)
# ============================================================

# Create sample input data (batch_size=5, features=4)
X_torch = torch.tensor([
    [1.0, 2.0, 3.0, 4.0],
    [2.0, 3.0, 4.0, 5.0],
    [3.0, 4.0, 5.0, 6.0],
    [4.0, 5.0, 6.0, 7.0],
    [5.0, 6.0, 7.0, 8.0]
], dtype=torch.float32)

# Create sample labels (batch_size=5)
y_torch = torch.tensor([0, 1, 2, 1, 0], dtype=torch.long)

In [2]:
# Network parameters
N = 4  # Input features
H = 8  # Hidden layer neurons
K = 3  # Output classes

# Define the network with ReLU and Softmax
class SimpleNetwork(nn.Module):
    def __init__(self, N, H, K):
        super(SimpleNetwork, self).__init__()
        self.fc1 = nn.Linear(N, H)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(H, K)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.softmax(x)
        return x

# Set manual seed for reproducibility
# torch.manual_seed(42)
# Create model
model = SimpleNetwork(N, H, K)

print("\n--- INITIAL WEIGHTS ---")
print(f"\nLayer 1 (fc1) Weight shape: {model.fc1.weight.shape}")
print(f"Layer 1 (fc1) Weight:\n{model.fc1.weight.data}")
print(f"\nLayer 1 (fc1) Bias shape: {model.fc1.bias.shape}")
print(f"Layer 1 (fc1) Bias:\n{model.fc1.bias.data}")

print(f"\nLayer 2 (fc2) Weight shape: {model.fc2.weight.shape}")
print(f"Layer 2 (fc2) Weight:\n{model.fc2.weight.data}")
print(f"\nLayer 2 (fc2) Bias shape: {model.fc2.bias.shape}")
print(f"Layer 2 (fc2) Bias:\n{model.fc2.bias.data}")



--- INITIAL WEIGHTS ---

Layer 1 (fc1) Weight shape: torch.Size([8, 4])
Layer 1 (fc1) Weight:
tensor([[ 0.3363,  0.4492, -0.0173,  0.0384],
        [ 0.4541,  0.3450,  0.2160,  0.2624],
        [ 0.0360,  0.3914,  0.2374,  0.0257],
        [-0.3615,  0.0407,  0.4945, -0.0804],
        [ 0.4241, -0.0100, -0.1647, -0.3752],
        [ 0.1003, -0.2219, -0.2816,  0.0066],
        [ 0.4285, -0.1387,  0.1907,  0.1666],
        [ 0.0710,  0.3106,  0.4807, -0.4778]])

Layer 1 (fc1) Bias shape: torch.Size([8])
Layer 1 (fc1) Bias:
tensor([ 0.3087, -0.3466, -0.3441, -0.3467, -0.3924,  0.1507, -0.4787, -0.0584])

Layer 2 (fc2) Weight shape: torch.Size([3, 8])
Layer 2 (fc2) Weight:
tensor([[-0.1110,  0.1522,  0.1340,  0.2432,  0.2070,  0.0760, -0.1721,  0.2685],
        [ 0.2563,  0.3016,  0.0837,  0.0438,  0.2179,  0.0017,  0.1902,  0.3218],
        [-0.0074, -0.1831,  0.1969, -0.1566, -0.1801,  0.1729,  0.1157,  0.2889]])

Layer 2 (fc2) Bias shape: torch.Size([3])
Layer 2 (fc2) Bias:
tensor([-0.1

In [3]:
# Define loss function and optimizer
# Note: Using NLLLoss with log_softmax for numerical stability
criterion = nn.NLLLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Forward pass
output = model(X_torch)
print(f"\n--- FORWARD PASS ---")
print(f"Model output shape: {output.shape}")
print(f"Model output (after softmax):\n{output}")

# Calculate loss (convert softmax to log for NLLLoss)
loss = criterion(torch.log(output + 1e-8), y_torch)
print(f"\nLoss: {loss.item():.6f}")

# Backward pass
optimizer.zero_grad()
loss.backward()

print("\n--- GRADIENTS ---")
print(f"\nLayer 1 (fc1) Weight gradient:\n{model.fc1.weight.grad}")
print(f"\nLayer 1 (fc1) Bias gradient:\n{model.fc1.bias.grad}")
print(f"\nLayer 2 (fc2) Weight gradient:\n{model.fc2.weight.grad}")
print(f"\nLayer 2 (fc2) Bias gradient:\n{model.fc2.bias.grad}")

# Update weights
optimizer.step()

print("\n--- UPDATED WEIGHTS ---")
print(f"\nLayer 1 (fc1) Weight:\n{model.fc1.weight.data}")
print(f"\nLayer 1 (fc1) Bias:\n{model.fc1.bias.data}")
print(f"\nLayer 2 (fc2) Weight:\n{model.fc2.weight.data}")
print(f"\nLayer 2 (fc2) Bias:\n{model.fc2.bias.data}")


--- FORWARD PASS ---
Model output shape: torch.Size([5, 3])
Model output (after softmax):
tensor([[0.2032, 0.6424, 0.1544],
        [0.1258, 0.7915, 0.0827],
        [0.0709, 0.8887, 0.0404],
        [0.0378, 0.9436, 0.0186],
        [0.0196, 0.9721, 0.0083]], grad_fn=<SoftmaxBackward0>)

Loss: 1.805842

--- GRADIENTS ---

Layer 1 (fc1) Weight gradient:
tensor([[ 0.5023,  0.6523,  0.8024,  0.9524],
        [ 0.3887,  0.5022,  0.6157,  0.7292],
        [-0.1064, -0.1377, -0.1690, -0.2002],
        [-0.1049, -0.1385, -0.1722, -0.2058],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.4048,  0.5269,  0.6491,  0.7712],
        [ 0.0703,  0.0913,  0.1123,  0.1334]])

Layer 1 (fc1) Bias gradient:
tensor([ 0.1500,  0.1135, -0.0313, -0.0337,  0.0000,  0.0000,  0.1222,  0.0210])

Layer 2 (fc2) Weight gradient:
tensor([[-1.0787, -1.6744, -0.8869, -0.2312,  0.0000,  0.0000, -0.7393, -0.3232],
        [ 1.5894,  2.4679,  1.3077,  0.3383,  0.0

In [4]:
# ============================================================
# TASK 2: Training with NumPy (ONE ITERATION) - ReLU + Softmax
# ============================================================

# Create sample input data
X_numpy = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [2.0, 3.0, 4.0, 5.0],
    [3.0, 4.0, 5.0, 6.0],
    [4.0, 5.0, 6.0, 7.0],
    [5.0, 6.0, 7.0, 8.0]
], dtype=np.float32)

# Create sample labels (one-hot encoded for cross-entropy)
y_numpy = np.array([0, 1, 2, 1, 0], dtype=np.int64)
y_onehot = np.zeros((5, 3))
y_onehot[np.arange(5), y_numpy] = 1

# Initialize weights with same seed
#np.random.seed(42)
W1 = np.random.randn(N, H).astype(np.float32) * 0.1
b1 = np.random.randn(H).astype(np.float32) * 0.1
W2 = np.random.randn(H, K).astype(np.float32) * 0.1
b2 = np.random.randn(K).astype(np.float32) * 0.1

print("\n--- INITIAL WEIGHTS ---")
print(f"\nLayer 1 Weight shape: {W1.shape}")
print(f"Layer 1 Weight:\n{W1}")
print(f"\nLayer 1 Bias shape: {b1.shape}")
print(f"Layer 1 Bias:\n{b1}")

print(f"\nLayer 2 Weight shape: {W2.shape}")
print(f"Layer 2 Weight:\n{W2}")
print(f"\nLayer 2 Bias shape: {b2.shape}")
print(f"Layer 2 Bias:\n{b2}")


--- INITIAL WEIGHTS ---

Layer 1 Weight shape: (4, 8)
Layer 1 Weight:
[[-0.03438075 -0.19718169 -0.182317    0.07423967  0.09144332 -0.06652517
   0.10324128  0.01646239]
 [ 0.09288841 -0.02363926 -0.16254033  0.07469751 -0.19452001  0.1342096
   0.06269707  0.11545358]
 [ 0.04251465  0.00104804  0.0613082  -0.08962058  0.17123224 -0.14740808
   0.11782735 -0.02280361]
 [ 0.04255986 -0.03911298  0.09220975  0.06412583 -0.09813917  0.098661
  -0.0764588  -0.08367795]]

Layer 1 Bias shape: (8,)
Layer 1 Bias:
[-0.03783407  0.12005955  0.01130718 -0.0059107  -0.08684349 -0.14468871
  0.07690652 -0.11731619]

Layer 2 Weight shape: (8, 3)
Layer 2 Weight:
[[ 0.01378909  0.03593726 -0.16518885]
 [ 0.09310158  0.01817475 -0.06288364]
 [ 0.03539157  0.00045008  0.12715875]
 [ 0.10328539 -0.16757806  0.1523586 ]
 [-0.06699377 -0.1475421  -0.01670514]
 [ 0.12971622 -0.00423073 -0.0339431 ]
 [ 0.04007223  0.05996702  0.07753114]
 [ 0.06045067 -0.00571326  0.00699186]]

Layer 2 Bias shape: (3,)
Lay

In [5]:
# Define activation functions
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(np.float32)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

def cross_entropy_loss(predictions, targets):
    n_samples = predictions.shape[0]
    return -np.sum(targets * np.log(predictions + 1e-8)) / n_samples

# Forward propagation
z1 = X_numpy @ W1 + b1  # Linear transformation
a1 = relu(z1)           # ReLU activation
z2 = a1 @ W2 + b2       # Linear transformation
a2 = softmax(z2)        # Softmax activation

print(f"\n--- FORWARD PASS ---")
print(f"Hidden layer output (after ReLU) shape: {a1.shape}")
print(f"Hidden layer output (after ReLU):\n{a1}")
print(f"Final output (after softmax) shape: {a2.shape}")
print(f"Model output (after softmax):\n{a2}")


--- FORWARD PASS ---
Hidden layer output (after ReLU) shape: (5, 8)
Hidden layer output (after ReLU):
[[0.4113454  0.         0.05667314 0.20536555 0.         0.00962508
  0.35318878 0.        ]
 [0.5549276  0.         0.         0.328808   0.         0.02856241
  0.5604956  0.        ]
 [0.69850975 0.         0.         0.45225042 0.         0.04749975
  0.76780266 0.        ]
 [0.8420919  0.         0.         0.57569283 0.         0.06643711
  0.9751095  0.        ]
 [0.98567414 0.         0.         0.69913524 0.         0.08537449
  1.1824164  0.        ]]
Final output (after softmax) shape: (5, 3)
Model output (after softmax):
[[0.33567423 0.3336303  0.33069548]
 [0.34092134 0.329922   0.32915664]
 [0.3458378  0.3252214  0.32894084]
 [0.3507768  0.3205435  0.32867974]
 [0.35573715 0.31588933 0.32837355]]


In [6]:
# Calculate loss
loss = cross_entropy_loss(a2, y_onehot)
print(f"\nLoss: {loss:.6f}")

# Backward pass
learning_rate = 0.01
n_samples = X_numpy.shape[0]

# Output layer gradients
dz2 = (a2 - y_onehot) / n_samples  # Gradient of loss w.r.t. z2
dW2 = a1.T @ dz2                    # Gradient w.r.t. W2
db2 = np.sum(dz2, axis=0)           # Gradient w.r.t. b2

# Hidden layer gradients
da1 = dz2 @ W2.T                    # Gradient w.r.t. a1
dz1 = da1 * relu_derivative(z1)     # Gradient w.r.t. z1 (ReLU derivative)
dW1 = X_numpy.T @ dz1               # Gradient w.r.t. W1
db1 = np.sum(dz1, axis=0)           # Gradient w.r.t. b1

print("\n--- GRADIENTS ---")
print(f"\nLayer 1 Weight gradient:\n{dW1}")
print(f"\nLayer 1 Bias gradient:\n{db1}")
print(f"\nLayer 2 Weight gradient:\n{dW2}")
print(f"\nLayer 2 Bias gradient:\n{db2}")

# Update weights
W1 -= learning_rate * dW1
b1 -= learning_rate * db1
W2 -= learning_rate * dW2
b2 -= learning_rate * db2

print("\n--- UPDATED WEIGHTS ---")
print(f"\nLayer 1 Weight:\n{W1}")
print(f"\nLayer 1 Bias:\n{b1}")
print(f"\nLayer 2 Weight:\n{W2}")
print(f"\nLayer 2 Bias:\n{b2}")


Loss: 1.096738

--- GRADIENTS ---

Layer 1 Weight gradient:
[[-0.07435135  0.          0.00373789  0.08230692  0.         -0.03192838
   0.0098249   0.        ]
 [-0.09912999  0.          0.00747578  0.10894925  0.         -0.04302764
   0.01317215  0.        ]
 [-0.12390863  0.          0.01121367  0.13559157  0.         -0.05412691
   0.0165194   0.        ]
 [-0.14868728  0.          0.01495156  0.1622339   0.         -0.06522617
   0.01986666  0.        ]]

Layer 1 Bias gradient:
[-0.02477864  0.          0.00373789  0.02664232  0.         -0.01109926
  0.00334725  0.        ]

Layer 2 Weight gradient:
[[-0.03643131 -0.05364761  0.09007893]
 [ 0.          0.          0.        ]
 [-0.00752988  0.00378157  0.00374831]
 [-0.02328277 -0.03500764  0.05829042]
 [ 0.          0.          0.        ]
 [-0.00238569 -0.00373043  0.00611612]
 [-0.0395507  -0.05941345  0.09896416]
 [ 0.          0.          0.        ]]

Layer 2 Bias gradient:
[-0.05421054 -0.0749587   0.12916925]

--- UPDAT